# Generated by Django 4.1 on 2022-08-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='Cédula'),
        ),
    ]
