# Generated by Django 4.1 on 2022-08-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('', ''), ('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cédula'),
        ),
    ]
