# Generated by Django 4.1 on 2022-08-24 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_athlete_gender_alter_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Athlete', to=settings.AUTH_USER_MODEL),
        ),
    ]
