# Generated by Django 4.1 on 2022-08-26 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osteo', '0001_initial'),
        ('users', '0005_alter_user_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='osteo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osteo.osteo'),
        ),
    ]
