# Generated by Django 4.1 on 2022-09-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
