# Generated by Django 4.1.4 on 2022-12-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_picture_alter_user_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='is_athlete',
            field=models.BooleanField(blank=True, null=True, verbose_name='Es deportista'),
        ),
    ]
