version: "3.8"
services:
  app:
    build: .
    depends_on:
      - mysql
    environment:
      DJANGO_SETTINGS_MODULE: metrics.settings.prod
      MYSQL_DATABASE: dinametrics
      MYSQL_USER: dina_user
      MYSQL_PASSWORD: dinametrics@2022*
      MYSQL_HOST: mysql
    volumes:
      - .:/django
    restart: on-failure
    ports:
      - 80:8000
    image: app:django
    container_name: django_container
      
    command: python manage.py runserver '0.0.0.0:8000'


  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_DATABASE: dinametrics
      MYSQL_USER: dina_user
      MYSQL_PASSWORD: dinametrics@2022*
      MYSQL_ROOT_PASSWORD: paloaltodinamtrics@2022*
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db:
    