version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 80:8000
    image: app:django
    container_name: django_container
    environment:
      DJANGO_SETTINGS_MODULE: metrics.settings.dev
    command: python manage.py runserver 0.0.0.0:8000
    