version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 80:8000
    image: app:django
    container_name: django_container
    command: gunicorn metrics.wsgi:application --bind 0.0.0.0:8000
    