# Generated by Django 4.1 on 2022-08-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_athlete_osteo'),
        ('osteo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osteo',
            name='athlete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.athlete'),
        ),
    ]
