# Generated by Django 4.1 on 2022-09-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteo', '0002_osteo_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='osteo',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='osteo',
            name='intensity',
            field=models.CharField(blank=True, max_length=2, verbose_name='Intensidad'),
        ),
    ]
