# Generated by Django 4.1 on 2022-09-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteo', '0003_osteo_observations_alter_osteo_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osteo',
            name='intensity',
            field=models.CharField(blank=True, max_length=30, verbose_name='Intensidad'),
        ),
    ]
