# Generated by Django 4.1 on 2022-11-11 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_user_picture_alter_user_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squat_score', models.FloatField(blank=True, null=True, verbose_name='Sentadilla | Puntuación Parcial')),
                ('squat_observations', models.TextField(blank=True, null=True, verbose_name='Sentadilla | Observaciones')),
                ('fence_step_l_score', models.FloatField(blank=True, null=True, verbose_name='Paso Izquierda | Puntuación Parcial')),
                ('fence_step_r_score', models.FloatField(blank=True, null=True, verbose_name='Paso Derecha | Puntuación Parcial')),
                ('fence_step_observations', models.TextField(blank=True, null=True, verbose_name='Paso | Observaciones')),
                ('lunge_l_score', models.FloatField(blank=True, null=True, verbose_name='Estocada Izquierda | Puntuación Parcial')),
                ('lunge_r_score', models.FloatField(blank=True, null=True, verbose_name='Estocada Derecha | Puntuación Parcial')),
                ('lunge_observations', models.TextField(blank=True, null=True, verbose_name='Estocada | Observaciones')),
                ('shoulder_l_score', models.FloatField(blank=True, null=True, verbose_name='Movilidad de hombros Izquierda | Puntuación Parcial')),
                ('shoulder_r_score', models.FloatField(blank=True, null=True, verbose_name='Movilidad de hombros Derecha | Puntuación Parcial')),
                ('shoulder_observations', models.TextField(blank=True, null=True, verbose_name='Movilidad de hombros | Observaciones')),
                ('leg_raise_l_score', models.FloatField(blank=True, null=True, verbose_name='Elevación Pierna Izquirda | Puntuación Parcial')),
                ('leg_raise_r_score', models.FloatField(blank=True, null=True, verbose_name='Elevación Pierna Derecha | Puntuación Parcial')),
                ('leg_raise_observations', models.TextField(blank=True, null=True, verbose_name='Elevación Pierna | Observaciones')),
                ('trunk_l_score', models.FloatField(blank=True, null=True, verbose_name='Estabilidad Tronco Flexion Izquirda | Puntuación Parcial')),
                ('trunk_r_score', models.FloatField(blank=True, null=True, verbose_name='Estabilidad Tronco Flexion Derecha | Puntuación Parcial')),
                ('trunk_observations', models.TextField(blank=True, null=True, verbose_name='Estabilidad Tronco Flexion | Observaciones')),
                ('trunk_rot_l_score', models.FloatField(blank=True, null=True, verbose_name='Estabilidad Tronco Rotación Izquirda | Puntuación Parcial')),
                ('trunk_rot_r_score', models.FloatField(blank=True, null=True, verbose_name='Estabilidad Tronco Rotación Derecha | Puntuación Parcial')),
                ('trunk_rot_observations', models.TextField(blank=True, null=True, verbose_name='Estabilidad Tronco Rotación | Observaciones')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Puntuación Total')),
                ('athlete', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.athlete')),
            ],
        ),
    ]
