# Generated by Django 4.1 on 2022-09-05 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_alter_athlete_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, max_length=30, verbose_name='Prueba')),
                ('test_slug', models.SlugField(blank=True, max_length=30, unique=True, verbose_name='Slug')),
                ('partial_score', models.FloatField(blank=True, verbose_name='Puntuación Parcial')),
                ('total_score', models.FloatField(blank=True, verbose_name='Puntuación Total')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('athlete', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.athlete')),
            ],
        ),
    ]
