# Generated by Django 4.1 on 2022-09-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_athlete_gender'),
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fms',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.athlete'),
        ),
        migrations.AlterField(
            model_name='fms',
            name='test',
            field=models.CharField(blank=True, choices=[('Sentadilla con brazos estirados', 'Sentadilla con brazos estirados'), ('Paso de valla', 'Paso de valla'), ('Estocada', 'Estocada'), ('Movilidad de hombros', 'Movilidad de hombros'), ('Elevación activa con la pierna recta', 'Elevación activa con la pierna recta'), ('Estabilidad de tronco en flexión', 'Estabilidad de tronco en flexión'), ('Estabilidad de tronco en rotación', 'Estabilidad de tronco en rotación')], max_length=50, verbose_name='Prueba'),
        ),
    ]
