# Generated by Django 4.1 on 2022-09-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0003_remove_fms_total_score_alter_fms_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fms',
            old_name='test',
            new_name='name',
        ),
    ]
