# Generated by Django 4.1 on 2022-09-06 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_athlete_gender'),
        ('fms', '0005_rename_partial_score_fms_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fms',
            old_name='observations',
            new_name='squat_observations',
        ),
        migrations.RenameField(
            model_name='fms',
            old_name='score',
            new_name='squat_score',
        ),
        migrations.RemoveField(
            model_name='fms',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fms',
            name='test_slug',
        ),
        migrations.AlterField(
            model_name='fms',
            name='athlete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.athlete'),
        ),
    ]
