# Generated by Django 4.1 on 2022-09-06 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_athlete_gender'),
        ('fms', '0006_rename_observations_fms_squat_observations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fms',
            old_name='squat_observations',
            new_name='observations',
        ),
        migrations.RenameField(
            model_name='fms',
            old_name='squat_score',
            new_name='score',
        ),
        migrations.AddField(
            model_name='fms',
            name='name',
            field=models.CharField(blank=True, choices=[('Sentadilla con brazos estirados', 'Sentadilla con brazos estirados'), ('Paso de valla', 'Paso de valla'), ('Paso de valla iz', 'Paso de valla Izquierda'), ('Paso de valla der', 'Paso de valla Derecha'), ('Estocada', 'Estocada'), ('Movilidad de hombros', 'Movilidad de hombros'), ('Elevación activa con la pierna recta', 'Elevación activa con la pierna recta'), ('Estabilidad de tronco en flexión', 'Estabilidad de tronco en flexión'), ('Estabilidad de tronco en rotación', 'Estabilidad de tronco en rotación')], max_length=50, verbose_name='Prueba'),
        ),
        migrations.AddField(
            model_name='fms',
            name='test_slug',
            field=models.SlugField(blank=True, max_length=30, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='fms',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.athlete'),
        ),
    ]
