# Generated by Django 4.1 on 2022-09-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0008_rename_observations_fms_squat_observations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fms',
            name='fence_step_l_observations',
            field=models.TextField(blank=True, null=True, verbose_name='Paso | Observaciones'),
        ),
        migrations.AddField(
            model_name='fms',
            name='fence_step_l_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Paso | Puntuación Parcial'),
        ),
        migrations.AlterField(
            model_name='fms',
            name='squat_observations',
            field=models.TextField(blank=True, null=True, verbose_name='Sentadilla | Observaciones'),
        ),
        migrations.AlterField(
            model_name='fms',
            name='squat_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Sentadilla | Puntuación Parcial'),
        ),
    ]
