# Generated by Django 4.1 on 2022-09-16 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_fv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('speed1', models.FloatField(blank=True, null=True, verbose_name='Velocidad 1')),
                ('speed2', models.FloatField(blank=True, null=True, verbose_name='Velocidad 2')),
                ('speed3', models.FloatField(blank=True, null=True, verbose_name='Velocidad 3')),
                ('speed4', models.FloatField(blank=True, null=True, verbose_name='Velocidad 4')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_fv', to='users.athlete')),
            ],
        ),
    ]
