# Generated by Django 4.1 on 2022-11-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_user_picture_alter_user_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='FV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('rm', models.FloatField(blank=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fv', to='users.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='FV_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('speed1', models.FloatField(blank=True, null=True, verbose_name='Velocidad 1')),
                ('speed2', models.FloatField(blank=True, null=True, verbose_name='Velocidad 2')),
                ('speed3', models.FloatField(blank=True, null=True, verbose_name='Velocidad 3')),
                ('speed4', models.FloatField(blank=True, null=True, verbose_name='Velocidad 4')),
                ('profile_fv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fv_register', to='profile_fv.fv')),
            ],
        ),
    ]
