# Generated by Django 4.1 on 2022-11-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_fv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fv',
            name='rm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
