# Generated by Django 4.1 on 2022-09-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_fv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_fv',
            name='speed1',
            field=models.FloatField(blank=True, default=0, verbose_name='Velocidad 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile_fv',
            name='speed2',
            field=models.FloatField(blank=True, default=0, verbose_name='Velocidad 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile_fv',
            name='speed3',
            field=models.FloatField(blank=True, default=0, verbose_name='Velocidad 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile_fv',
            name='speed4',
            field=models.FloatField(blank=True, default=0, verbose_name='Velocidad 4'),
            preserve_default=False,
        ),
    ]
