# Generated by Django 4.1 on 2022-09-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_fv', '0002_alter_profile_fv_speed1_alter_profile_fv_speed2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_fv',
            name='speed1',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidad 1'),
        ),
        migrations.AlterField(
            model_name='profile_fv',
            name='speed2',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidad 2'),
        ),
        migrations.AlterField(
            model_name='profile_fv',
            name='speed3',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidad 3'),
        ),
        migrations.AlterField(
            model_name='profile_fv',
            name='speed4',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidad 4'),
        ),
    ]
