# Generated by Django 4.1 on 2022-11-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_picture_alter_user_document'),
        ('profile_fv', '0004_alter_fv_rm'),
    ]

    operations = [
        migrations.CreateModel(
            name='FV_observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fv_observations', to='users.athlete')),
            ],
        ),
    ]
