# Generated by Django 4.1 on 2022-09-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('jump', models.CharField(blank=True, choices=[('SJ', 'SJ'), ('CMJ', 'CMJ'), ('DROPS', 'DROPS'), ('Q', 'Q')], max_length=5, null=True, verbose_name='Salto')),
                ('left', models.FloatField(blank=True, null=True, verbose_name='Izquierda')),
                ('right', models.FloatField(blank=True, null=True, verbose_name='Derecha')),
                ('deficit', models.FloatField(blank=True, null=True, verbose_name='Déficit')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilateral', to='users.athlete')),
            ],
        ),
    ]
