# Generated by Django 4.1 on 2022-11-21 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_picture_alter_user_document'),
        ('bilateral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilateralObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilateral_observations', to='users.athlete')),
            ],
        ),
    ]
