# Generated by Django 4.1.4 on 2022-12-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_user_picture_alter_user_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fat_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('is_athlete', models.BooleanField(blank=True, verbose_name='Es deportista')),
                ('triceps', models.FloatField(blank=True, verbose_name='Triceps')),
                ('subscap', models.FloatField(blank=True, verbose_name='Subescapular')),
                ('abdominal', models.FloatField(blank=True, verbose_name='Abdominal')),
                ('suprailiac', models.FloatField(blank=True, verbose_name='Suprailiaco')),
                ('thigh', models.FloatField(blank=True, verbose_name='Muslo')),
                ('calf', models.FloatField(blank=True, verbose_name='Pantorrilla')),
                ('fat_rate', models.FloatField(blank=True, verbose_name='Porcentaje de grasa')),
                ('athlete', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.athlete')),
            ],
        ),
    ]
