# Generated by Django 4.1.4 on 2022-12-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fat_rate',
            name='is_athlete',
            field=models.BooleanField(blank=True, null=True, verbose_name='Es deportista'),
        ),
    ]
