# Generated by Django 4.1.4 on 2022-12-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0002_alter_fat_rate_is_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fat_rate',
            name='fat_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje de grasa'),
        ),
    ]
