# Generated by Django 4.1.4 on 2022-12-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_picture_alter_user_document'),
        ('fat', '0003_alter_fat_rate_fat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fat_rate',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fats', to='users.athlete'),
        ),
    ]
