# Generated by Django 4.1.4 on 2022-12-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0004_alter_fat_rate_athlete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fat_rate',
            name='is_athlete',
        ),
    ]
