# Generated by Django 4.1.4 on 2022-12-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_athlete_is_athlete'),
        ('fat', '0005_remove_fat_rate_is_athlete'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fat_observations', to='users.athlete')),
            ],
        ),
    ]
