# Generated by Django 4.1 on 2022-09-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0009_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SJ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month1", models.FloatField(blank=True, verbose_name="Mes 1")),
                ("month2", models.FloatField(blank=True, verbose_name="Mes 2")),
                ("month3", models.FloatField(blank=True, verbose_name="Mes 3")),
                ("month4", models.FloatField(blank=True, verbose_name="Mes 4")),
                ("month5", models.FloatField(blank=True, verbose_name="Mes 5")),
                ("month6", models.FloatField(blank=True, verbose_name="Mes 6")),
                ("month7", models.FloatField(blank=True, verbose_name="Mes 7")),
                ("month8", models.FloatField(blank=True, verbose_name="Mes 8")),
                ("month9", models.FloatField(blank=True, verbose_name="Mes 9")),
                ("month10", models.FloatField(blank=True, verbose_name="Mes 10")),
                ("month11", models.FloatField(blank=True, verbose_name="Mes 11")),
                ("month12", models.FloatField(blank=True, verbose_name="Mes 12")),
                (
                    "athlete",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.athlete",
                    ),
                ),
            ],
        ),
    ]
