# Generated by Django 4.1 on 2022-09-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuro", "0004_alter_sj_month1_alter_sj_month10_alter_sj_month11_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmj",
            name="month1",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 1"),
        ),
        migrations.AlterField(
            model_name="cmj",
            name="month10",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 10"),
        ),
        migrations.AlterField(
            model_name="cmj",
            name="month11",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 11"),
        ),
        migrations.AlterField(
            model_name="cmj",
            name="month12",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 12"),
        ),
        migrations.AlterField(
            model_name="cmj",
            name="month2",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 2"),
        ),
        migrations.AlterField(
            model_name="cmj",
            name="month3",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 3"),
        ),
        migrations.AlterField(
            model_name="cmj",
            name="month4",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 4"),
        ),
        migrations.AlterField(
            model_name="cmj",
            name="month5",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 5"),
        ),
        migrations.AlterField(
            model_name="cmj",
            name="month6",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 6"),
        ),
        migrations.AlterField(
            model_name="cmj",
            name="month7",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 7"),
        ),
        migrations.AlterField(
            model_name="cmj",
            name="month8",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 8"),
        ),
        migrations.AlterField(
            model_name="cmj",
            name="month9",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 9"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month1",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 1"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month10",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 10"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month11",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 11"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month12",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 12"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month2",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 2"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month3",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 3"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month4",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 4"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month5",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 5"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month6",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 6"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month7",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 7"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month8",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 8"),
        ),
        migrations.AlterField(
            model_name="drops",
            name="month9",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 9"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month1",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 1"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month10",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 10"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month11",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 11"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month12",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 12"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month2",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 2"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month3",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 3"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month4",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 4"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month5",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 5"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month6",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 6"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month7",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 7"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month8",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 8"),
        ),
        migrations.AlterField(
            model_name="q",
            name="month9",
            field=models.FloatField(blank=True, null=True, verbose_name="Mes 9"),
        ),
    ]
