# Generated by Django 4.1 on 2022-10-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuro", "0005_alter_cmj_month1_alter_cmj_month10_alter_cmj_month11_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cmj", name="month1",),
        migrations.RemoveField(model_name="cmj", name="month10",),
        migrations.RemoveField(model_name="cmj", name="month11",),
        migrations.RemoveField(model_name="cmj", name="month12",),
        migrations.RemoveField(model_name="cmj", name="month2",),
        migrations.RemoveField(model_name="cmj", name="month3",),
        migrations.RemoveField(model_name="cmj", name="month4",),
        migrations.RemoveField(model_name="cmj", name="month5",),
        migrations.RemoveField(model_name="cmj", name="month6",),
        migrations.RemoveField(model_name="cmj", name="month7",),
        migrations.RemoveField(model_name="cmj", name="month8",),
        migrations.RemoveField(model_name="cmj", name="month9",),
        migrations.RemoveField(model_name="drops", name="month1",),
        migrations.RemoveField(model_name="drops", name="month10",),
        migrations.RemoveField(model_name="drops", name="month11",),
        migrations.RemoveField(model_name="drops", name="month12",),
        migrations.RemoveField(model_name="drops", name="month2",),
        migrations.RemoveField(model_name="drops", name="month3",),
        migrations.RemoveField(model_name="drops", name="month4",),
        migrations.RemoveField(model_name="drops", name="month5",),
        migrations.RemoveField(model_name="drops", name="month6",),
        migrations.RemoveField(model_name="drops", name="month7",),
        migrations.RemoveField(model_name="drops", name="month8",),
        migrations.RemoveField(model_name="drops", name="month9",),
        migrations.RemoveField(model_name="q", name="month1",),
        migrations.RemoveField(model_name="q", name="month10",),
        migrations.RemoveField(model_name="q", name="month11",),
        migrations.RemoveField(model_name="q", name="month12",),
        migrations.RemoveField(model_name="q", name="month2",),
        migrations.RemoveField(model_name="q", name="month3",),
        migrations.RemoveField(model_name="q", name="month4",),
        migrations.RemoveField(model_name="q", name="month5",),
        migrations.RemoveField(model_name="q", name="month6",),
        migrations.RemoveField(model_name="q", name="month7",),
        migrations.RemoveField(model_name="q", name="month8",),
        migrations.RemoveField(model_name="q", name="month9",),
        migrations.RemoveField(model_name="sj", name="month1",),
        migrations.RemoveField(model_name="sj", name="month10",),
        migrations.RemoveField(model_name="sj", name="month11",),
        migrations.RemoveField(model_name="sj", name="month12",),
        migrations.RemoveField(model_name="sj", name="month2",),
        migrations.RemoveField(model_name="sj", name="month3",),
        migrations.RemoveField(model_name="sj", name="month4",),
        migrations.RemoveField(model_name="sj", name="month5",),
        migrations.RemoveField(model_name="sj", name="month6",),
        migrations.RemoveField(model_name="sj", name="month7",),
        migrations.RemoveField(model_name="sj", name="month8",),
        migrations.RemoveField(model_name="sj", name="month9",),
        migrations.AddField(
            model_name="cmj",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cmj",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drops",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drops",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="q", name="date", field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="q",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sj", name="date", field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sj",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
