# Generated by Django 4.1 on 2022-10-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("neuro", "0006_remove_cmj_month1_remove_cmj_month10_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cmj", name="date",),
        migrations.RemoveField(model_name="cmj", name="score",),
        migrations.RemoveField(model_name="drops", name="date",),
        migrations.RemoveField(model_name="drops", name="score",),
        migrations.RemoveField(model_name="q", name="date",),
        migrations.RemoveField(model_name="q", name="score",),
        migrations.RemoveField(model_name="sj", name="date",),
        migrations.RemoveField(model_name="sj", name="score",),
    ]
