# Generated by Django 4.1 on 2022-10-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuro", "0007_remove_cmj_date_remove_cmj_score_remove_drops_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmj",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cmj",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drops",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drops",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="q", name="date", field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="q",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sj", name="date", field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sj",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
