# Generated by Django 4.1 on 2022-10-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuro", "0008_cmj_date_cmj_score_drops_date_drops_score_q_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmj",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drops",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="q",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sj",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
