# Generated by Django 4.1 on 2022-11-21 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_picture_alter_user_document'),
        ('neuro', '0009_alter_cmj_score_alter_drops_score_alter_q_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuroObservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neuro_observations', to='users.athlete')),
            ],
        ),
    ]
